nav:
  - Home: index.md
  - Model:
      - Basic model: models/models.md
      - Inheritance: models/inheritance.md
      - Json: models/json.md
      - Annotation: models/annotation.md
  - Schema:
      - Basic: schema/basic.md
      - Object: schema/object.md
      - Array: schema/array.md
      - Nested object: schema/nested_object.md
      - Nested array: schema/nested_array.md
      - Enums: schema/enum.md
  - Field: field.md
  - Providers: providers.md
  - Examples: examples.md
  - Database:
      - Setup: database/setup.md
      - Connect: database/connect.md
      - CRUD operations: database/crud.md
      - Operators: database/operators.md
      - Query: database/query.md
  - Enums: enums.md

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list

site_name: Models Manager
